servers:
# example:
#   ip: example.com
#   port: 25565
#   name: Example
# hub:
#   ip: hub-ip.com
#   port: 25565
#   name: HubListener

strings:
  transferring: "<green>Joining {{SERVER}}..."
  transferred: "<gray>{{PLAYER}} joined {{SERVER}}"

  config-reloaded: "<yellow>Config reloaded! If you don't see your changes applied, restart the server."

  server-not-exist: "<red>That server doesn't exist!"
  server-config-incorrect: "<red>The config for this server is broken!"

  playerlist-list: "<green>On {{SERVER}} are currently {{PLAYERS}} players online:\n    {{ONLINE_PLAYERS}}"
  playerlist-no-respond: "<red> The Server didn't responded to the status request"

  custom-no-data: "<red>There is no server stored in this slot!"
  custom-already-data: "<red>There is already a server stored in this slot!"
  custom-deleted: "<green>The server under this slot has been deleted."
  custom-added: "<green>Added a new custom server."

# Enables the /hub command and it's alias as an alias for "/join hub".
enable-hub: false
# Teleport players to hub when the server is shutting down/restarting
hub-on-stop: false
# Remove Join messages
remove-join-msg: false
# HubUtil Mode
# - Disables door, trapdoor and item frame changing
# - Clears inventory
# - Tp's player to 0 0 0, 0 0 on join
hub:
  enabled: false
  spawn:
    x: 0
    y: 0
    z: 0
  interactable-blocks:
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - OAK_PRESSURE_PLATE
    - STONE_PRESSURE_PLATE
    - OAK_BUTTON
    - STONE_BUTTON
