servers:
# example:
#   ip: example.com
#   port: 25565
#   name: Example
# hub:
#   ip: hub-ip.com
#   port: 25565
#   name: Hub

strings:
  transferring: "<green>Joining {{SERVER}}..."
  transferred: "<gray>{{PLAYER}} joined {{SERVER}}"

  config-reloaded: "<yellow>Config reloaded! If you don't see your changes applied, restart the server."

  server-not-exist: "<red>That server dosen't exist!"
  server-config-incorrect: "<red>The config for this server is broken!"

# Enables the /hub command and it's alias as an alias for "/join hub".
enable-hub: false
# Remove Join messages
remove-join-msg: false
